# fly.toml app configuration file generated for microonion on 2023-05-17T19:18:39+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "microonion"
primary_region = "mad"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
